version: "3.8"

services:
  app:
    image: nama-app-anda
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run deploy
