export const FITNESS_GOALS = {
  WEIGHT_LOSS: "WEIGHT_LOSS",
  WEIGHT_GAIN: "WEIGHT_GAIN",
  BODY_BUILDING: "BODY_BUILDING",
  MUSCLE_GAIN: "MUSCLE_GAIN",
  ENDURANCE_TRAINING: "ENDURANCE_TRAINING",
  FLEXIBILITY_IMPROVEMENT: "FLEXIBILITY_IMPROVEMENT",
  GENERAL_FITNESS: "GENERAL_FITNESS",
  STRESS_RELIEF: "STRESS_RELIEF",
};
